- name: Docker run
  hosts: 103.127.96.18
  become: true

  tasks:
    - name: Install Docker Compose
      ansible.builtin.package:
        name: docker-compose
        state: present

    - name: Run docker-compose up -d
      ansible.builtin.command:
        cmd: "docker-compose up -d"
        chdir: "/home/paul/"
      become: true
      become_user: root