- name: Install Docker on Ubuntu
  hosts: 103.127.96.18
  become: true
  tasks:

    - name: Update and install required packages
      apt: 
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

    - name: Add Docker's official GPG key
      apt_key:
         url: https://download.docker.com/linux/ubuntu/gpg
         state: present

    - name: Add Docker repository
      apt_repository:
        repo: 
          "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        update_cache: yes
        state: present

    - name: Install Docker and related packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Enable and start Docker services
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - docker.service
        - containerd.service

    - name: Add user to Docker group
      ansible.builtin.user:
        name: paul
        groups: docker
        append: yes